#!/bin/sh
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin

badrequest() {
        echo 'Status: 400 Bad Request'
        echo
        exit 1
}

echo 'Access-Control-Allow-Origin: *'

batctl if | cut -d: -f1 | grep -xqF "$QUERY_STRING" || badrequest

exec ../../../bin/gluon-neighbour-info -s nodeinfo -i "$QUERY_STRING" -d ff02::2:1001 -p 1001 -r nodeinfo
