#!/bin/sh

#PATH=/home/jj/FF/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin

cat <<EOF
Access-Control-Allow-Origin: *
Content-type: application/json

EOF

exec ../../bin/gluon-neighbour-info -d ::1 -p 1001 -t 1 -c 1 -r nodeinfo
